### ISSUE TITLE
Adding hover effect

### ISSUE THREAD

**Issue by KavyaBS123** [07sumit1002/CabRental#10]
Hovering effect can be added to the best services section on each car
![Screenshot (463)](https://github.com/07sumit1002/CabRental/assets/148982177/58c8fbf0-1fbc-4093-9947-5414439b4d2e)

**Comment by 07sumit1002** [comment]
@KavyaBS123 Go ahead and work on it.

**Comment by 07sumit1002** [comment]
good work @KavyaBS123
