### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by Khushalsarode** [07sumit1002/CabRental#100]
1. Improve & Update Readme file 
2. adding workflows for raising issue template

**Comment by nagajaideep** [comment]
@Khushalsarode hey i also have an separate pull request i want to know to link pull request to this issue bro can you explain once

**Comment by SaanyaGarg5** [comment]
you can assign that task to me under gsso-ext and Hacktoberfest label..

**Comment by Mahesh2k5** [comment]
hey I want to improve Readme file with proper directions. I'm a beginner can you please let me work on this

**Comment by Khushalsarode** [comment]
> @Khushalsarode hey i also have an separate pull request i want to know to link pull request to this issue bro can you explain once

what i understand from your query is: you want to know how to link issue to PR you raise? correct

so when you raise issue it has one number prefix by '#'

when you raise PR add '# and issue number' it will link and when use 'closes #number' it will close issue when merge or closed.

did you got it!

@nagajaideep

**Comment by nagajaideep** [comment]
yeah got it after an yt tutorial

**Comment by Khushalsarode** [comment]
do we need to add gssoc and gssoc-ext labels here as this programs has been merged?
@07sumit1002 then this PR get counts!
