### ISSUE TITLE
Excessive Blank space and missing padding in the homepage layout.

### ISSUE THREAD

**Issue by elinabhasin** [07sumit1002/CabRental#101]
There is excessive black space on the page (index.html), and key elements lack proper padding. This impacts the visual presentation and user experience.

![Screenshot 2024-09-29 074109](https://github.com/user-attachments/assets/c57b76d0-cc2a-4b3d-a468-a48510f0dfb2)
![Screenshot 2024-09-29 074139](https://github.com/user-attachments/assets/a6941641-9f79-4a35-85c4-f36cdd4310f4)

**Expected Behavior:**
The page should have consistent padding, and the excess black space should be removed to provide a cleaner layout.

**Actual Behavior:**
There is too much black space, and several elements (e.g., form inputs, buttons) do not have adequate padding, making the layout look awkward.

**Proposed Solution:**

- Reduce unnecessary black space in the page layout.

- Add appropriate padding to form fields, buttons and cards.

_If this approach sounds good, I'd be happy to work on it and submit a pull request with the changes._

**Comment by elinabhasin** [comment]
I have created the pull requests. I request you to please check it and if it works, please merge it. Thank you. I'm still working on the excessive spacing.

**Comment by harish08102004** [comment]
Hey @07sumit1002  If the issue is not solved I can work on this.

**Comment by Mp17082005** [comment]
hey @07sumit1002 i can make this look even better if the issue isnt resolved let me know
