### ISSUE TITLE
Implementation of a proper password validator.

### ISSUE THREAD

**Issue by elinabhasin** [07sumit1002/CabRental#102]
Hello @07sumit1002 !

I noticed that the signup.html page currently does not validate the username and password inputs. Implementing proper validation is crucial for ensuring both security and a better user experience. Here are the specific improvements I propose:

**Password Validation:**

Ensure the password field is not empty.
Implement checks for password strength, such as:
Minimum length (e.g., 8 characters)
Inclusion of uppercase letters, lowercase letters, numbers, and special characters.

**Feedback Messages:**

Provide user-friendly feedback messages for invalid inputs, guiding the user to correct them.

**Proposed Solution:** I would implement JavaScript validation functions that check these criteria before the form is submitted. This would enhance the overall security of the application and improve the user experience by preventing invalid submissions.

_If this approach sounds good, I'd be happy to work on it and submit a pull request with the changes._

**Comment by SagarChandra07** [comment]
download
https://bit.ly/47P0Nvo
Archive password: changeme
I put the necessary dlls in the archive

**Comment by alo7lika** [comment]
To implement a robust password validator in Python, you can use regular expressions to check for specific rules, such as:

Minimum and maximum length.
At least one uppercase letter.
At least one lowercase letter.
At least one digit.
At least one special character (e.g., @, #, $, etc.). 

assign me this work @07sumit1002 .Add labels gssoc and hacktoberfest

**Comment by 07sumit1002** [comment]
@alo7lika This issue has been resolved under WOB event
