### ISSUE TITLE
Lacking proper alignment and padding.

### ISSUE THREAD

**Issue by elinabhasin** [07sumit1002/CabRental#103]
I was going through the serv.html file and came across areas with no proper alignment of text and buttons within a box or a card. This makes the ui less visually appealing.
![Screenshot 2024-09-29 075432](https://github.com/user-attachments/assets/f2e26fa8-2cbe-4a8c-8861-8936e2ccd917)

Proposed Solution:

- Adding text and buttons alignment to the layout.

- Adding appropriate padding to form fields, buttons and cards.

If this approach sounds good, I'd be happy to work on it and submit a pull request with the changes.

**Comment by SagarChandra07** [comment]
This might help:This file might fix it

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Pass: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by elinabhasin** [comment]
Hello! I've fixed the alignment and padding.
If it works for you.. please consider merging it. Thank you!
