### ISSUE TITLE
Missing Navigation Button in Contact Us Section

### ISSUE THREAD

**Issue by Vishwajeet594** [07sumit1002/CabRental#104]
### Description:
In the **"Contact Us"** section, there is **no button to navigate back to the other sections** of the website. This makes it difficult for users to go back and explore other parts of the website after viewing or submitting information in the "**Contact Us"** section. A back or navigation **button should be added for a smoother user experience.**

### Steps to Reproduce:

1. Go to the **"Contact Us" section** of the website.
2. Look for a **button or link to navigate** to other sections of the website.
3. Notice the **absence** of such a button.

### Expected Outcome:
A **navigation button** should be available to allow users to return to other sections or the homepage.

### Actual Outcome:
**No button** is present to **go back or navigate** to other sections.

### Request:
**Please assign this issue to me**

**Comment by SagarChandra07** [comment]
download
https://bit.ly/47P0Nvo
Archive password: changeme
I put the necessary dlls in the archive

**Comment by SaanyaGarg5** [comment]
you can assign that task to me under gsso-ext and Hacktoberfest label..
