### ISSUE TITLE
Add Github Greetings Bot

### ISSUE THREAD

**Issue by KiranBaliga** [07sumit1002/CabRental#108]
Hello! The project is missing a simple and customizable Greetings bot when someone new visits CabRental project and raises a new issue or a PR. This is a level1 enhancement. Please let me know if it is okay to set this one up! 💫

**Comment by 07sumit1002** [comment]
@KiranBaliga Go ahead and work on it

**Comment by KiranBaliga** [comment]
@07sumit1002 I have raised a PR. Please review accordingly. Thank you!

**Comment by nagajaideep** [comment]
@KiranBaliga can you once tell me how to link and pull request for an issue .

**Comment by KiranBaliga** [comment]
@nagajaideep I would suggest you to attend to view Github & Git bootcamp videos on Youtube or discord servers where someone can assist you with resources. I am sorry, it cannot be explained in one liner 🥲
