### ISSUE TITLE
redirection and saving the credentials of the users

### ISSUE THREAD

**Issue by Madhuri243** [07sumit1002/CabRental#109]
Hello @07sumit1002 
It will be better to validate the sign in credentials with storing them in database and store the registerd user in the database
 and validate the user with the information stored with us 
Allow only people who have proper credential
If you like this one I will start working  on it

**Comment by 07sumit1002** [comment]
@Madhuri243 Go ahead and work on it

**Comment by Madhuri243** [comment]
@07sumit1002 please review my pull request
