### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by KavyaBS123** [07sumit1002/CabRental#11]
I didn't get the use of adding admin button, instead we can add login button and create a login page for that
![Screenshot (465)](https://github.com/07sumit1002/CabRental/assets/148982177/d55cdfd4-7e0a-4fa4-b864-6956e3410a41)

**Comment by 07sumit1002** [comment]
@KavyaBS123 Go ahead and work on it. Since this section will depend on your creativity the points will be assigned accordingly.
