### ISSUE TITLE
Complicated file structure

### ISSUE THREAD

**Issue by DarshanKrishna-DK** [07sumit1002/CabRental#112]
Modifying the complicated, messy file structure to an organised file structure which will help in better understanding and tracking related files/ folders.

**Comment by SaanyaGarg5** [comment]
you can assign that task to me under gsso-ext and Hacktoberfest label..

**Comment by DarshanKrishna-DK** [comment]
hey @SaanyaGarg5. Good to see that you are interested to take up this issue, but i have already been assigned with this issue and currently working on it.

**Comment by DarshanKrishna-DK** [comment]
Hey @07sumit1002. While simplifying the file structure, i had to go through the entire project and change the required file/ image paths in the code. So can you add level2 tag for this? Also can you add hactoberfest and gssoc labels/ tags as well for this issue? 

I have created a pull request for this issue - https://github.com/07sumit1002/CabRental/pull/241

Thank you!
