### ISSUE TITLE
Update Twitter Icon to "X" Icon

### ISSUE THREAD

**Issue by Vishwajeet594** [07sumit1002/CabRental#113]
### Description:
As Twitter has recently rebranded to "X", we need to replace the old Twitter icon across the platform with the new "X" icon. This change is crucial to maintaining our platform's **up-to-date and consistent design**.

### Tasks:
Replace the Twitter icon with the "X" icon.
### Current Twitter Icon:
![Screenshot 2024-09-29 225037](https://github.com/user-attachments/assets/2b73f947-e7c0-4692-a1e3-26e885cf9a02)

**Comment by Subashree-selvaraj** [comment]
can you assign this issue to me!

**Comment by SaanyaGarg5** [comment]
you can assign that task to me under gsso-ext and Hacktoberfest label..

**Comment by Shalinis19137** [comment]
Not only logo its need to change all  "colors of logo " as they have and i worked on it . Please assign this to me.
