### ISSUE TITLE
Change red to green for better user experience

### ISSUE THREAD

**Issue by elinabhasin** [07sumit1002/CabRental#117]
Currently, the color red is being used in the Values and Principles section of the About page . While red can be attention-grabbing, it often conveys negative emotions like danger or warning, which may affect the user's mindset in a way that isn't desirable for this context.

Proposed Change:
I recommend replacing the red color with green. Green is commonly associated with positivity, growth, and calm, which could improve the user experience by creating a more reassuring and positive interaction.

Rationale:
Psychological Impact: Green is known to evoke feelings of relaxation and trust, whereas red can invoke urgency, stress, or caution.
Improved User Engagement: Green is more suitable for encouraging user interaction in a calm and reassuring way.

Consistency: Since the page uses alot of red, we can change that to the colors with complement green better as well.

Expected Behavior:
The color of the element should be changed to green for better psychological alignment with user expectations.

I'd love to work on this issue. I request you to assign it to me so i can start creating pull requests to enhance the UI. Thank you!
![Screenshot 2024-09-30 081252](https://github.com/user-attachments/assets/9d497740-3b2a-4fd2-b987-9128d9aed6f6)

**Comment by nagajaideep** [comment]
i would like to work on this can you please assign me the this issue @elinabhasin @07sumit1002

**Comment by harish08102004** [comment]
Hey @07sumit1002 @elinabhasin I would like to make these changes

**Comment by ChauhanAyush04** [comment]
@07sumit1002 I want to work on this issue under GSSOC 2024. Please assign me this.

**Comment by SaanyaGarg5** [comment]
you can assign that task to me under gsso-ext and Hacktoberfest label..

**Comment by harish08102004** [comment]
Hey @elinabhasin are you still working on this ?

**Comment by akbatra567** [comment]
PR merged: https://github.com/07sumit1002/CabRental/pull/121
