### ISSUE TITLE
Add Missing Logos in Front of Email, Address, and Phone Information (Not Visible)

### ISSUE THREAD

**Issue by Vishwajeet594** [07sumit1002/CabRental#120]
### Description:
It has been noticed that **the logos/icons in front of the email, address, and phone information are not visible** in the app. These icons are necessary to improve the clarity and user-friendliness of the contact information.

### Screenshot
![Screenshot 2024-09-30 144633](https://github.com/user-attachments/assets/b0674898-1fbc-47ae-96e9-276d6fff18ed)

**Comment by Subashree-selvaraj** [comment]
can you assign this to me!

**Comment by harish08102004** [comment]
hey @Vishwajeet594  I can work on this issue
