### ISSUE TITLE
ADDITION OF ISSUE,FEATURE AND PULL REQUEST TEMPLATES

### ISSUE THREAD

**Issue by nagajaideep** [07sumit1002/CabRental#122]
i would like to add these 3 templates to the repo .Could you please assign me this issue @07sumit1002

**Comment by Shalinis19137** [comment]
I am going to make your templates more attractive by adding some moving functionalities . Please assign me this issue

**Comment by nagajaideep** [comment]
the pull request has been made please review it and close this issue @07sumit1002
