### ISSUE TITLE
Align 'Frequently Asked Questions' Section to Center

### ISSUE THREAD

**Issue by satyam1024** [07sumit1002/CabRental#123]
Description: The "Frequently Asked Questions" (FAQ) section is not centrally aligned like the other sections on the page. This creates an inconsistent layout and affects the visual harmony of the website.
Centering this section will provide a cleaner, more uniform appearance and make the page visually appealing.
screenshot 
![Screenshot (2991)](https://github.com/user-attachments/assets/98a21bbe-0222-4142-8f5c-80d14057741f)

I'd love to work on this issue. I request you to assign it to me . Thank you!

**Comment by SaanyaGarg5** [comment]
you can assign that task to me under gsso-ext and Hacktoberfest label..

**Comment by Ibrangrd** [comment]
I will do it in less time and effectively.

**Comment by Jyothishree2k5** [comment]
@07sumit1002 can you assign this issue to me please?!
