### ISSUE TITLE
Enhancing Readme.md

### ISSUE THREAD

**Issue by neeru24** [07sumit1002/CabRental#134]
Hi,

I’ve been exploring the project and appreciate the work you’ve done so far. I’d like to propose an update to the README.md file as It seems a bit boring to read and I want to improve it  to provide a more comprehensive overview of the website. Here are a few ideas I have in mind:

1. A detailed description of the project.
2. A clear vision for the final project and any future enhancements.
3. Embedded links for additional reference.

I believe these updates could enhance user understanding and engagement with the project. If you're open to it, I’d love to contribute.

I’m committed to continually improving the quality of our documentation.

Thank you!

**Comment by alo7lika** [comment]
Assign me this issue.I have worked on this and I m a beginner

**Comment by AnujSaha0111** [comment]
I want to work on it. Can you please assign it to me?

**Comment by neeru24** [comment]
> Hey @neeru24, I see your PR was closed #171 with the label duplicate.
> 
> Could you have a look at the current readme and see areas of improvement ?
> 
> If you could restyle the current version, we can keep this issue open or else will close and create a new one. Do let me know here. Thanks in advance.

Hi, Yes 
I can improve this readme.  Should I start my work and create a PR?
Or I've to create another issue?

**Comment by akbatra567** [comment]
> > Hey @neeru24, I see your PR was closed #171 with the label duplicate.
> > 
> > Could you have a look at the current readme and see areas of improvement ?
> > 
> > If you could restyle the current version, we can keep this issue open or else will close and create a new one. Do let me know here. Thanks in advance.
> 
> Hi, Yes 
> I can improve this readme.  Should I start my work and create a PR?
> Or I've to create another issue?
> 
> 

This issue is fine, do create a new PR.

**Comment by neeru24** [comment]
> > > Hey @neeru24, I see your PR was closed #171 with the label duplicate.
> > > Could you have a look at the current readme and see areas of improvement ?
> > > If you could restyle the current version, we can keep this issue open or else will close and create a new one. Do let me know here. Thanks in advance.
> > 
> > 
> > Hi, Yes
> > I can improve this readme.  Should I start my work and create a PR?
> > Or I've to create another issue?
> 
> This issue is fine, do create a new PR.

Sure, I will create a PR by evening.

**Comment by neeru24** [comment]
> > > Hey @neeru24, I see your PR was closed #171 with the label duplicate.
> > > Could you have a look at the current readme and see areas of improvement ?
> > > If you could restyle the current version, we can keep this issue open or else will close and create a new one. Do let me know here. Thanks in advance.
> > 
> > 
> > Hi, Yes
> > I can improve this readme.  Should I start my work and create a PR?
> > Or I've to create another issue?
> 
> This issue is fine, do create a new PR.

@akbatra567 I've submitted the PR that got merged but it is not there in leaderboard, can you assign me labels again and mark it as completed or close the issue

**Comment by akbatra567** [comment]
> > > > Hey @neeru24, I see your PR was closed #171 with the label duplicate.
> > > > Could you have a look at the current readme and see areas of improvement ?
> > > > If you could restyle the current version, we can keep this issue open or else will close and create a new one. Do let me know here. Thanks in advance.
> > > 
> > > 
> > > Hi, Yes
> > > I can improve this readme.  Should I start my work and create a PR?
> > > Or I've to create another issue?
> > 
> > 
> > This issue is fine, do create a new PR.
> 
> @akbatra567 I've submitted the PR that got merged but it is not there in leaderboard, can you assign me labels again and mark it as completed or close the issue

There is no PR that got merged yet, I've added a requested some changes to the PR. Do have a look at that. 
Also as a practice in future do tag issue with your PR so it automatically closes once the PR is merge. 
For now I've added:  `closes #134` in PR description, which automatically closes the issue as soon as PR is merged.
