### ISSUE TITLE
Add User Profile Photo to Customer Reviews Section.

### ISSUE THREAD

**Issue by avi4748sinha** [07sumit1002/CabRental#135]
In the current design of the Customer Reviews section, there's a missing element that would significantly enhance the user experience and trust factor: the user or client’s profile photo. Adding a visual representation of the reviewer will make the testimonials more personal, relatable, and authentic. The profile photo should be displayed next to the reviewer’s name and rating.

I propose implementing this feature by integrating a section for profile photos, ensuring they are properly styled to fit seamlessly with the existing layout. This will not only add visual appeal but also help in building credibility for the reviews. If assigned this issue, I will make the necessary frontend adjustments and test the feature to ensure smooth functionality across devices.
![Screenshot_20241002-163722](https://github.com/user-attachments/assets/9625f510-2800-48e5-9a6c-43589ce140c1)

**Comment by alo7lika** [comment]
Assign me this work, i would love to contribute.Add labels gssoc and hacktoberfest

**Comment by avi4748sinha** [comment]
> Assign me this work, i would love to contribute.Add labels gssoc and hacktoberfest

😂😂Hey, u can find something new might be interesting to work on ur interest 😂please don't snatch my issues😂😂😂

**Comment by avi4748sinha** [comment]
Thanks @07sumit1002  I will do it shortly

**Comment by akbatra567** [comment]
PR already merged: https://github.com/07sumit1002/CabRental/pull/165
