### ISSUE TITLE
Change Twitter Symbol to X in footer section

### ISSUE THREAD

**Issue by kundana29** [07sumit1002/CabRental#143]
I would like to propose a change to update the Twitter symbol to "X" in to reflect Twitter's recent rebranding. This change ensures consistency with the platform's new identity and avoids any potential confusion for users. please assign this issue to me
![Screenshot 2024-10-03 092808](https://github.com/user-attachments/assets/f62a6f19-af5b-4ef1-986b-8cc1473a7ef8)

**Comment by avi4748sinha** [comment]
I can do it instantly with perfection.
