### ISSUE TITLE
Dark mode implementation for your cool website 

### ISSUE THREAD

**Issue by STDYGIT** [07sumit1002/CabRental#147]
HEY @07sumit1002  it will be so cool to make your website in dark theme too with these cool switch 
![Screenshot 2024-10-02 at 12 44 47 PM](https://github.com/user-attachments/assets/be29a4f7-d1d5-480f-a5bc-5f109867aa29)
![Screenshot 2024-10-02 at 12 44 31 PM](https://github.com/user-attachments/assets/65e28c24-c37b-4cf6-a8cf-fb6e62043f8c)

**Comment by STDYGIT** [comment]
Sir, I would like to work on this feature and would appreciate it if you could assign it to me for Hacktoberfest and GGSOC '24. I believe this is a level 2 task / level 3 task, as it requires a complete overhaul of the page styles. Thank you!

**Comment by akbatra567** [comment]
Hey @STDYGIT ,
Quick question on implementation, would you be just changing the color of the theme toggle switch or would also be adding dark theme styles of different pages, components and fonts ?

**Comment by STDYGIT** [comment]
For info I have completed this feature on the website and the owner had merged too and I had changed the whole website theme style and colors

**Comment by akbatra567** [comment]
> For info I have completed this feature on the website and the owner had merged too and I had changed the whole website theme style and colors

For future references, 
Tag the related issues with the PR, use keyword `closes` in the PR description so it automatically closes the open issue related to it so it doesn't give an impression that it is yet to be worked upon.

Example: 
```
Closes #147
```

Read more here: https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue
