### ISSUE TITLE
Creating Contact us form

### ISSUE THREAD

**Issue by Yaser-123** [07sumit1002/CabRental#15]
Creating contact us form using HCJ and implemention backend and google sheets

https://github.com/07sumit1002/CabRental/assets/140265777/b614fdf6-cf35-41e7-83c2-68b66bc5fecb

**Comment by Yaser-123** [comment]
Bro i will add all the details u need istead of my mail and number

**Comment by 07sumit1002** [comment]
@Yaser-123 Go ahead and work on it. If you feel that these points are insufficient, we can discuss.

**Comment by 07sumit1002** [comment]
Although i have assigned the points I think it would be better to open the contact form in a pop-up instead of opening it on a new page(when that page doesn't have any pop up)?
