### ISSUE TITLE
Introduction of Dark Theme Button

### ISSUE THREAD

**Issue by synakr** [07sumit1002/CabRental#159]
It's a really beautiful website, with vibrant color, but to make it full-fledged website I'd really appreciate if I get the chance to work on the dark theme/version of this website using some eye-pleasing dark color schemes, for those who would like to take the least amount of stress on their eyes!

A rough idea of the color scheme that comes to my mind:
![web](https://github.com/user-attachments/assets/b84905da-4887-4e6b-8214-4db3fcfb4e41)

Still! I'll try my best to bring something new to the table! Thank you!

**Comment by alo7lika** [comment]
assign me this work @07sumit1002
