### ISSUE TITLE
Enhance UI of Footer

### ISSUE THREAD

**Issue by anushkajjadhav** [07sumit1002/CabRental#161]
<img width="1685" alt="Screenshot 2024-10-04 at 2 40 47 PM" src="https://github.com/user-attachments/assets/672b8fe4-792b-425a-af5b-178e76b96703">

For this footer i can improve:
-Aesthetics
-Alignment
-Add contact us box
-Provide social media links with icons too

Please assign this to me under Wob and gssoc-ext

**Comment by Shalinis19137** [comment]
Can you please assign me this project under Gssocs-ext2024
