### ISSUE TITLE
Add content to how it works

### ISSUE THREAD

**Issue by anushkajjadhav** [07sumit1002/CabRental#167]
<img width="1681" alt="Screenshot 2024-10-04 at 5 33 25 PM" src="https://github.com/user-attachments/assets/21082f45-ed95-4436-bb89-820d43767970">

-The sample content can be replaced with proper content
-Styling can be improved
-Alignment can be fixed

pls assign to me under gssoc-ext and WOB

**Comment by devikakanyal** [comment]
i would like to work on it. please assign it to me

**Comment by anushkajjadhav** [comment]
@07sumit1002 Can you pls add the hactoberfest label too

**Comment by akbatra567** [comment]
PR already merged https://github.com/07sumit1002/CabRental/pull/205. Closing the issue.
