### ISSUE TITLE
[DOCS]Add images and the Relevant Data of the cabs.

### ISSUE THREAD

**Issue by harshit1arora** [07sumit1002/CabRental#193]
Hey,
I want to add the relevant images and data like the cost of the cab per day. This will help the user to choose between the comfortable rides, and cabs available.

Please assign this task to me, as I want to work on it.
![car](https://github.com/user-attachments/assets/ba22bce9-40f6-4a1a-bf27-3882710198b8)

**Comment by alo7lika** [comment]
assign me this work @07sumit1002

**Comment by Sarthakkashyapp** [comment]
Hi @07sumit1002 I would like to work on this issue.

**Comment by Jotthecode** [comment]
assign me this work @07sumit1002
