### ISSUE TITLE
Enhance the UI for "Leave a Review" form

### ISSUE THREAD

**Issue by swathivemula7** [07sumit1002/CabRental#199]
I would like to enhance the UI of the "Leave a review" form..  like adding placeholders for each field and making the form's UI more relevant to the theme of the website.
![review-gssoc](https://github.com/user-attachments/assets/beee3daf-2d2d-4408-9026-3dea4cc8c360)

@07sumit1002 Kindly assign me for this issue under the labels gssoc-ext and hacktoberfest.

**Comment by 07sumit1002** [comment]
@swathivemula7  Pull the latest code and then work on it

**Comment by swathivemula7** [comment]
> @swathivemula7 Pull the latest code and then work on it

ok..i will start working on it...
