### ISSUE TITLE
Enhance UI for the contact form

### ISSUE THREAD

**Issue by swathivemula7** [07sumit1002/CabRental#201]
The current contact form in the website is not well aligned...so i would like to align it properly and make it more relevant to the entire website..

![Capturekfr](https://github.com/user-attachments/assets/e2988ebd-4b37-4351-83f9-9cfc3e5dafeb)
@07sumit1002 Kindly assign me this issue under the labels gssoc-ext and hacktoberfest.

**Comment by 07sumit1002** [comment]
Pull the latest code and then work on it

**Comment by swathivemula7** [comment]
> Pull the latest code and then work on it

ok..i will start working on it...

**Comment by bhaviya18** [comment]
@swathivemula7 can you please assign this task to me

**Comment by swathivemula7** [comment]
> @swathivemula7 can you please assign this task to me
Hi @bhaviya18 ,
This issue is assigned to me and I am currently working on this issue..

**Comment by swathivemula7** [comment]
@07sumit1002 I have raised a PR for this issue, kindly review at the earliest..
