### ISSUE TITLE
[FEATURE]  enchance the about page 

### ISSUE THREAD

**Issue by jyothimanoj12** [07sumit1002/CabRental#208]
i want to improve the ui of the about page to this
![Screenshot 2024-10-05 185101](https://github.com/user-attachments/assets/340d53db-f3c3-4196-8620-274e01607e7a)
![Screenshot 2024-10-05 185127](https://github.com/user-attachments/assets/4fe17fb3-ec16-498b-94dd-d0f8e1940c77)
![Screenshot 2024-10-05 185140](https://github.com/user-attachments/assets/5d9461f3-9d5b-45c6-8015-61f0125cbd1c)

added a footer section too

![Screenshot 2024-10-05 185203](https://github.com/user-attachments/assets/7c757ece-47fa-47ff-991d-8bc007cb2a8a)

plz allow me to work on this issue under gsoc ext

**Comment by jyothimanoj12** [comment]
plz add hacktober -accepted tag and level tag too

**Comment by 07sumit1002** [comment]
@jyothimanoj12  Change the navbar to match with other pages as well.

**Comment by jyothimanoj12** [comment]
> @jyothimanoj12 Change the navbar to match with other pages as well.

Will do it

**Comment by jyothimanoj12** [comment]
done 👍

**Comment by jyothimanoj12** [comment]
#240

**Comment by jyothimanoj12** [comment]
done 👍
