### ISSUE TITLE
Adding Dark mode to other pages(About, service) since its applied to only Home page.

### ISSUE THREAD

**Issue by Deepika14145** [07sumit1002/CabRental#211]
Topic:
Dark mode is only added to the Home page not applied to other pages and the logo in the Home page does not match with Background in Dark mode.

Details:
Adding Dark mode to other pages will make the website more attractive and users can switch between Dark and light modes as per convenience since in the original website dark mode is only applied to the Home page. 

Benefits:
1) Making UI more interactive.
2) Making Both themes available to users so that they can switch between both.

![Screenshot 2024-10-05 214217](https://github.com/user-attachments/assets/f8dde03c-b14f-4956-a2c7-1c4992ee3d6c)
![Screenshot 2024-10-05 214234](https://github.com/user-attachments/assets/980de382-aa6d-49fa-a66a-b2c4a817f6ac)

Please assign me this task @sanjay-kv , @rakeshkushwaha332, @akbatra567 , @KiranBaliga, I will try to make this website more attractive.
also add tags like GSSoC-Extd. |  Hacktoberfest-accepted | Lavels.

**Comment by prishsha** [comment]
I would also like to work on this. Can this issue be assigned to me?

**Comment by 07sumit1002** [comment]
Pull the latest code and then work on it

**Comment by Deepika14145** [comment]
Okay

**Comment by Deepika14145** [comment]
Applied changes, please review it.

**Comment by gauranshivarshney** [comment]
I would also like to work on this. Can this issue be assigned to me?
