### ISSUE TITLE
Update Cab Images, Names and Prices 

### ISSUE THREAD

**Issue by itsshreyanigam** [07sumit1002/CabRental#214]
![Screenshot 2024-10-04 144451](https://github.com/user-attachments/assets/51724c16-af4e-4544-99fd-a88aadd7f8eb)

Please assign me this task so i can work upon this.
Also please add GSSoC Extd. , Hactoberfest and Level label

**Comment by 07sumit1002** [comment]
Pull the latest code and then work on it
