### ISSUE TITLE
[FEATURE] Ride-Sharing Feature

### ISSUE THREAD

**Issue by shreyad2806** [07sumit1002/CabRental#216]
**Please describe your feature request related to a problem?**
> A one liner title for feature
Ride-Sharing Feature

**Describe your solution to problem**
> A clear and concise description of what you want to happen.
dd a ride-sharing feature where users can split vehicle rental costs with others, allowing multiple users to book the same vehicle for a single trip.

**Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
> Add any other context or screenshots about the feature request here.

**Add Relevant Screenshot (if available)**
> add here

**Comment by 07sumit1002** [comment]
@shreyad2806 Try to write the problem and solution heading on your own instead of copying from somewhere
