### ISSUE TITLE
[FEATURE] Develop the home page

### ISSUE THREAD

**Issue by pranusri1903** [07sumit1002/CabRental#217]
**Please describe your feature request related to a problem?**
enhance the page with the betterment of the theme

**Describe your solution to problem**
Make minor changes to built a better one
To make divs with css and js modifications
Also to remove the red outline in the forms

**Describe alternatives you've considered**
change the entire theme adding some animations 

**Additional context**
Also add a documentation near the home screen car in the empty side

**Additional comment**
gssoc-ext Level 2 work kind i suppose

**Comment by 07sumit1002** [comment]
@pranusri1903 Try to write the problem and solution heading on your own instead of copying from somewhere
