### ISSUE TITLE
[BUG] Correct hover effect on header

### ISSUE THREAD

**Issue by SurajSG23** [07sumit1002/CabRental#224]
Hey, i noticed that in your header when we hover the mouse the text-decoration underline is not properly working! 

ScreenShot:

![image](https://github.com/user-attachments/assets/7b6d3afe-4b00-43ee-b955-5387422b054d) 

Please assign me this task, I would like to fix it under GSSoC and hacktober fest.Thank You 🙏

**Comment by 07sumit1002** [comment]
Now it is resolved 
Pull the latest code and check
