### ISSUE TITLE
Forgot Password Page

### ISSUE THREAD

**Issue by prishsha** [07sumit1002/CabRental#228]
Forgot Password Page in case the user has signed in but cannot recollect password

There will be a forgot password redirection link right below the new user option which will redirect users to a forgot password page. Here, on entering their username, they will receive a pop-up that the verification code has been sent to their email.

![image](https://github.com/user-attachments/assets/6d60e479-a0a2-482b-b61c-46bf90a1630b)

The link would be added here. I will keep in mind the overall UI/UX of the page and accordingly develop the page. Kindly assign me this issue under the labels gssoc-ext, hactoberfest-accepted and specify the level of the issue @07sumit1002  @AniketFirke @aadii0408

**Comment by 07sumit1002** [comment]
Pull the latest code and then work on it

**Comment by prishsha** [comment]
![image](https://github.com/user-attachments/assets/d5ae7cc3-182f-4adb-9f30-22d0bba99ca0)

- [ X] Link to Forgot Password added on Login page

![image](https://github.com/user-attachments/assets/d9051539-a822-43e2-b218-2d85c64aade8)

- [ X] Separate forgot password page created with same UI/UX. New files for forgot-password html and css

![image](https://github.com/user-attachments/assets/049f3f5a-3593-416d-b056-d874e2b0617e)

- [ X] Alert displays when input fields are filled and submit button is clicked

Should I go ahead and issue a pull request? @07sumit1002

**Comment by AniketFirke** [comment]
Yes, you can do that.

**Comment by AniketFirke** [comment]
Congratulations!
