### ISSUE TITLE
Adding a Pop-up notification if any of the fields are empty during booking

### ISSUE THREAD

**Issue by prishsha** [07sumit1002/CabRental#229]
A pop-up notification would ask the user to fill all the fields if any of the field is empty while booking the cab. Also, the webpage has a bug in the dark mode where the input values are not visible. 

The current website allows user to click on the Book Now button irrespective of whether all the input fields are filled. 

This can be improved by 
- Adding a * next to the field so that the user knows that it is mandatory to be filled
- Sending an alert if user tries to Book a Cab when any of the fields are empty
- Fixing the color of the input values in dark mode

![image](https://github.com/user-attachments/assets/a6f0e108-7c56-4874-a3eb-50647b36bf88)
![image](https://github.com/user-attachments/assets/d200d9d6-2fd3-47f6-9523-1d6de383f79a)

Kindly assign me this issue under the labels hacktoberfest-accepted, gssoc-ext and level of the problem @07sumit1002 @aadii0408

**Comment by 07sumit1002** [comment]
Pull the latest code and then work on it

**Comment by Shalinis19137** [comment]
I would like to work on this project , Can you please assign me this issue.

**Comment by prishsha** [comment]
HI @07sumit1002 i have generated a pull request for this issue almost a week back. Could you please take a look
