### ISSUE TITLE
Add Testimonials Section to Website

### ISSUE THREAD

**Issue by Yaser-123** [07sumit1002/CabRental#23]
We need to add a testimonials section to our website to showcase feedback and reviews from our satisfied users. This will help build credibility and trust with potential new users.
Tasks:
1.Design the Testimonials Section
2.Implement the Frontend
3.Add Functionality
4.Testing and Quality Assurance

**Comment by 07sumit1002** [comment]
@Yaser-123  Go ahead and work on it. Since this design will depend on your creativity, the points will be assigned accordingly.
