### ISSUE TITLE
add hacktoberfest and GSSOC 24 ext  labels

### ISSUE THREAD

**Issue by alo7lika** [07sumit1002/CabRental#232]
ADD LABELS ON THE MAIN CAR RENTAL PAGE OTHERWISE THE PROJECT WONT BE COUNTED IN THE hacktoberfest

(Your PR/MR was submitted to a repository that is not participating in Hacktoberfest. Maintainers need to add the hacktoberfest topic to the repository, or add the hacktoberfest-accepted label to your PR/MR.

For more information about how exactly we validate PR/MRs for contributors, check the [details on our participation page](https://hacktoberfest.com/participation/#pr-mr-details).)

**Comment by 07sumit1002** [comment]
Ok can you help me with the issues and pr where I have to add the tags.

**Comment by alo7lika** [comment]
![Screenshot 2024-10-06 130427](https://github.com/user-attachments/assets/a45b9dc7-c286-4947-8076-3e153e7002b0)
![Screenshot 2024-10-06 130444](https://github.com/user-attachments/assets/f543a3db-2348-40b7-be04-f6adf6897924)

**Comment by alo7lika** [comment]
@07sumit1002  i have attached the screenshots of where you should add the labels

**Comment by 07sumit1002** [comment]
ok Thanks will do so

**Comment by 07sumit1002** [comment]
Can you check if this is correct
and thanks for informing about it
