### ISSUE TITLE
[DOCS] Adding documentation on the home page

### ISSUE THREAD

**Issue by pranusri1903** [07sumit1002/CabRental#234]
Our cab rental service is designed to provide you with a seamless, safe, and comfortable travel experience. Whether you're heading to a business meeting, exploring the city, or need a reliable ride to the airport, we've got you covered with our fleet of modern, well-maintained vehicles.
Our mission is to provide safe, reliable, and affordable transportation solutions that cater to individual and corporate needs. We prioritize customer satisfaction and strive to set the benchmark for cab rental services.

The documentation is needed on the home page because there's a huge noticable gap below "Want to share or rent a cab" heading and its not good.

<img width="1440" alt="Screenshot 2024-10-06 at 1 44 40 PM" src="https://github.com/user-attachments/assets/518faf1f-7e4a-4fc2-992e-a7db7b7eb79d">

@07sumit1002 Please assign this to me so that i could do it.

**Comment by 07sumit1002** [comment]
Pull the latest code and then work on it

**Comment by pranusri1903** [comment]
Thanks a lot
