### ISSUE TITLE
[Improving home page styling]

### ISSUE THREAD

**Issue by pranusri1903** [07sumit1002/CabRental#236]
Hey I believe that you website could do better with some styling improvements.
Such as,
<img width="1440" alt="Screenshot 2024-10-06 at 1 51 07 PM" src="https://github.com/user-attachments/assets/260d2638-bd7c-4b57-b8e3-64f2444acf2a">
The red outline around the details to be filled is not looking good so I could find a better way to do it better.
Also the boxes have strict corners which would look better with some round corners.
And the when we hover over the book now button, the whole button comes up but what I think would be better is if we hover over the button, the book now text gets bigger not the whole button maintaining the aesthetics of the website.

@07sumit1002 Please assign me this issue so that I could make it better.

**Comment by pranusri1903** [comment]
The navigation bar is not consistent across all the pages. 
Also hovering over the contents in the nav bar creates a inconsistent selection block.
The image of the latter is attached.
<img width="1440" alt="Screenshot 2024-10-06 at 7 34 55 PM" src="https://github.com/user-attachments/assets/6a2771a9-acf6-41e1-a51a-e825bafd38ec">
Selecting "Home" creates a P shape selection while hovering over it and it is same with the other objects of nav bar as well.
Please assign the task to me with required labels of gssoc-ext and the labels you think it satisfied to have it done smoothly.
Looking forward to you favourable response.

**Comment by 07sumit1002** [comment]
@pranusri1903 Please go through navbar of all the pages and make them consistent I will assign it level 3

**Comment by 07sumit1002** [comment]
Pull the latest code and then work on it

**Comment by pranusri1903** [comment]
Thanks a lot

**Comment by pranusri1903** [comment]
Done
