### ISSUE TITLE
Bug - Add different cars and pricing

### ISSUE THREAD

**Issue by poorvikaa08** [07sumit1002/CabRental#243]
I have noticed that all the cars in the rental section are named and priced the same. 
It is recommended to add different car names and pricing.

Screenshot 📸 
![image](https://github.com/user-attachments/assets/cc340702-d2ae-4356-85ca-080a1b6065ad)

@07sumit1002 
Assign it to me under gssoc-ext and hacktoberfest.
Thank you

**Comment by akbatra567** [comment]
This might be not relevant now: https://07sumit1002.github.io/CabRental/index.html
Do have a look @poorvikaa08, closing for now, if you still find the issue there. 
Do tag me and reopen the issue with assign you the same. 


<img width="1700" alt="Screenshot 2024-10-15 at 01 09 35" src="https://github.com/user-attachments/assets/1746eea9-b6fe-4f26-8c3f-651e9c76b0f2">
