### ISSUE TITLE
Adding Favicon to all webpages

### ISSUE THREAD

**Issue by VihaShomikha** [07sumit1002/CabRental#245]
Problem: Favicon is present only for the home page whereas other webpages doesn't have favicons. 

Solution: Simple modification in the HTML files. 

Please assign me this issue with the labels WOB, Hacktoberfest and GSSOC-EXTD @07sumit1002

**Comment by akbatra567** [comment]
Hey @VihaShomikha, 
Assigned you the issue. assigned level 1 for now. Will update based on the changes you made.
Do tag the issue with the PR when you create one, like `closes #245`

**Comment by VihaShomikha** [comment]
Hey @akbatra567. I have added the favicons and created the pull request. Do look into it. Thank you!
