### ISSUE TITLE
Add "About Us" Page to the Cab Rental Website

### ISSUE THREAD

**Issue by shreya-2410** [07sumit1002/CabRental#25]
Description
We need to create an "About Us" page for our cab rental website. This page should provide visitors with essential information about our company, including our overview, mission and vision, and values and principles.

Content Requirements
Company Overview

Brief history and founding details.
Overview of services offered.
Any relevant milestones or achievements.
Mission and Vision

Clear statement of the company’s mission.
Vision for the future.
Values and Principles

List of core values.
Description of guiding principles.

before
![image](https://github.com/07sumit1002/CabRental/assets/137192044/3e45ffcd-5b78-45d1-9f28-21e7b3850de7)

after 
![image](https://github.com/07sumit1002/CabRental/assets/137192044/5b1edc8d-3c0b-456b-bf48-d1ac3b41d872)
pls assign this to me in vsoc

**Comment by 07sumit1002** [comment]
@shreya-2410  Go ahead and work on it. Since this design will depend on your creativity the points will be assigned accordingly. Additionally, do not forget to include the navbar on the page.
