### ISSUE TITLE
Adding Custom Cursor effect

### ISSUE THREAD

**Issue by ShrishtiSingh26** [07sumit1002/CabRental#250]
### Unique cursor designs can capture users' attention and make the interaction, encouraging them to engage more with your content.

Please assign this to me , I am ready for this
Thankyou!

**Comment by ChauhanAyush04** [comment]
@07sumit1002  plz assign me

**Comment by YasirKhan231** [comment]
Hey @07sumit1002  assign this issue i will make chnages within a day

**Comment by akbatra567** [comment]
Hey @ShrishtiSingh26, 
Could you share some ideas on what `Custom Cursor effect` are you talking about and would be adding ?

**Comment by ShrishtiSingh26** [comment]
@akbatra567 yeah basically I wish to customize the cursor design and add a trail to it when dragged around
Something like this

https://github.com/user-attachments/assets/5cb126e6-85a8-44a2-afb4-25c5d18e863c


https://github.com/user-attachments/assets/d5944105-9879-471b-b610-243b9f2afd1a

**Comment by ShrishtiSingh26** [comment]
so if you wish I can start working on this feature

**Comment by akbatra567** [comment]
Sure, I think first would look good. 
Could you make this reusable for all pages ? @ShrishtiSingh26

**Comment by ShrishtiSingh26** [comment]
@akbatra567 yup sure, I will make It  work out for all the pages
