### ISSUE TITLE
[DOCS]

### ISSUE THREAD

**Issue by pranusri1903** [07sumit1002/CabRental#253]
**Problem**
In the login page
If the person has no account
the option given for them is "Not signed u? Sign in" which should be opposite 
It should be "Don't have an account? Sign up"
<img width="443" alt="Screenshot 2024-10-06 at 7 45 29 PM" src="https://github.com/user-attachments/assets/6115b08a-0bd8-4a05-8b20-d16b1b81a222">

Please assign the PR to me for I could do that in mins.
Please add the required labels of gssoc extended and levels and hacktober as you see fit.
Looking forward to you reply.

**Comment by pranusri1903** [comment]
Also when we move to the login page
The website logo disappears, I will add that as well. 
Its an easy but easily not noticable to naked eye.
Please assign me this PR to make it right
<img width="1440" alt="Screenshot 2024-10-06 at 7 50 40 PM" src="https://github.com/user-attachments/assets/e7ecea2a-a1da-4142-9de2-a4c30023cd47">

**Comment by pranusri1903** [comment]
@07sumit1002

**Comment by akbatra567** [comment]
Hey @pranusri1903, 
Assigning you the issue for the changes you mentioned :

```
the option given for them is "Not signed u? Sign in" which should be opposite
It should be "Don't have an account? Sign up"
```

> For the other favicon icon, there is already another issue which talks about syncing all favicon for all pages. So closing this issue. #245

**Comment by pranusri1903** [comment]
the option given for them is "Not signed up? Sign in" which should be opposite
It should be "Don't have an account? Sign up"

For this, I have submited an ongoing PR waiting or reveiw with updated navs and this documentation correction as I saw.
PR number #302.
I will add the rest documentation in the PR I submit for this one.
Hope thats fine

**Comment by akbatra567** [comment]
@pranusri1903, 
Just a callout, It is fine for me to close two issues for with one PR. 

But it might be bad for calculating points for you, as number of PR is counted and not the number of issues. even for hacktoberfest as well as other programs.

**Comment by pranusri1903** [comment]
> @pranusri1903, Just a callout, It is fine for me to close two issues for with one PR.
> 
> But it might be bad for calculating points for you, as number of PR is counted and not the number of issues. even for hacktoberfest as well as other programs.

ohh wait then, i will make a new PR for this issue adding some more documentation!

**Comment by akbatra567** [comment]
Hey @pranusri1903,
Just a callout for future.

1. make one PR for only one issue
2. name PR correctly
3. do not add a lot of things in one issue. or add everything to description and not in the comments.
