### ISSUE TITLE
[GENERAL] Bug :- on the login page it should be signup but it is signin

### ISSUE THREAD

**Issue by tarunkumar2005** [07sumit1002/CabRental#255]
**Topic**
on the login page it should be signup but it is signin this needs to be fixed for better ui/ux

**Additional context**
![image](https://github.com/user-attachments/assets/2863c6c7-6dcf-47c4-a6ec-f1176945cc34)

@07sumit1002 Assign this to me under gssoc 2024 ext and hacktoberfest i will work on this.

**Comment by akbatra567** [comment]
Already an issue created and assigned to resolve the same: https://github.com/07sumit1002/CabRental/issues/253
hence closing the issue.
