### ISSUE TITLE
Local storage and Ui improvement of the form

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [07sumit1002/CabRental#264]
I want to work on the Ui of this form as this can be improved and add local storage to store the user input.
@07sumit1002  can you please assign me this task.

**Comment by pameladeysarkar2003** [comment]
please assign the task to me @07sumit1002

**Comment by akbatra567** [comment]
Hey @T-Rahul-prabhu-38, 
Could be elaborate a bit on how would this help ?

**Comment by T-Rahul-prabhu-38** [comment]
i can use Js to save the userdata in json format, this can be later retrived for backend if needed.

**Comment by akbatra567** [comment]
What value would it add in the current scope ? Let's say we save it, but do we even need to retrieve it ?

Is there any form that big which needs to be cached in order that the data is not lost ?

**Comment by T-Rahul-prabhu-38** [comment]
😂😂😂 it adds value to my leaderboard ranking.

tbf its not that useful, but good to have .
