### ISSUE TITLE
Contact page Needs More Interactive display

### ISSUE THREAD

**Issue by ThunderShadows** [07sumit1002/CabRental#274]
The contact us page looks static and needs some good interaction and format.

@07sumit1002 

I want to improve the styling and the responsiveness of the page by adding CSS elements and making it more interactive

**Comment by akbatra567** [comment]
Already interactive, closing for now. Do tag me with what more you can add to the page, will reopen this issue.
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/35e0cf48-7f2b-4f68-98e7-5f36770ab44e">

https://07sumit1002.github.io/CabRental/contactus.html?
