### ISSUE TITLE
[DOCS] Image in README.md Not Displaying

### ISSUE THREAD

**Issue by neeru24** [07sumit1002/CabRental#311]
Hi,
I noticed that the image in the README.md file is not displaying correctly. It seems there may be an issue with the image path or file reference. I would like to investigate and fix this by:

1. Ensuring the correct path to the image is provided.
2. Checking the image hosting (if external) to ensure it's available and accessible.
3. Testing the display to confirm the issue is resolved once the image is visible.

Could you please assign me this issue? I’ll submit a PR once the image is properly displaying.

Thank you!

![image](https://github.com/user-attachments/assets/032f37df-d679-48b1-ab24-7b627d326db0)

@07sumit1002 assign me. Please

**Comment by Brijeshthummar02** [comment]
hi there, @neeru24 i can fix it assign me.

**Comment by akbatra567** [comment]
This is already fixed in the current readme file. Closing this issue,
