### ISSUE TITLE
[FEATURE]add multilingual feature for the website.

### ISSUE THREAD

**Issue by SanikaBhalerao1345** [07sumit1002/CabRental#368]
**Please describe your feature request related to a problem?**
> users from different regions/foreigners visiting for travel purpose must be provided with multilingual feature in website 

**Describe your solution to problem**
> can add select language in footer region.
![image](https://github.com/user-attachments/assets/b0937800-c723-4974-b3b7-43466f9a3ffd)

**Describe alternatives you've considered**
> NA

**Additional context**
> NA

**Add Relevant Screenshot (if available)**
> NA

**Comment by akbatra567** [comment]
Hey @SanikaBhalerao1345 ,
Could you tell how would you achieve this ?

**Comment by SanikaBhalerao1345** [comment]
@akbatra567 Thanks for assigning me.
I will use Google api for this.what do you think?

**Comment by akbatra567** [comment]
@SanikaBhalerao1345, 
As you can see currently all the pages are html pages, so I would suggest find a way to avoid adding same code to each page and you can write a reusable code or script which can be directly imported would be a great option. 

Google api would be good, thanks for telling.
