### ISSUE TITLE
Query inputs

### ISSUE THREAD

**Issue by ridanoorain** [07sumit1002/CabRental#37]
It is not accepting any input including travel date and departure time
![Screenshot (15)](https://github.com/07sumit1002/CabRental/assets/173170420/341de926-a563-4a89-a4de-48f7b2310d72)

**Comment by 07sumit1002** [comment]
![image](https://github.com/07sumit1002/CabRental/assets/98510898/de7bc806-b3b4-4f83-84d5-fb312f1978b7)
![image](https://github.com/07sumit1002/CabRental/assets/98510898/8dfc30c9-6e72-4a83-a63a-76b6bced2014)
These are working fine if you tap on the icon (Calendar, cloack)

**Comment by 07sumit1002** [comment]
If you have any good approach please suggest

**Comment by ridanoorain** [comment]
It would be better if the text color of the input was black

**Comment by 07sumit1002** [comment]
OK Sure go ahead and work on it
