### ISSUE TITLE
Proper alignment of the steps

### ISSUE THREAD

**Issue by ridanoorain** [07sumit1002/CabRental#38]
![Screenshot (14)](https://github.com/07sumit1002/CabRental/assets/173170420/b11b2ae8-c10a-4c82-98f5-4f82e6fb5da3)

**Comment by 07sumit1002** [comment]
@ridanoorain Go ahead and work on it.

**Comment by KavyaBS123** [comment]
Hey @07sumit1002 I am VSOC Contributor I  can work on this issue and make it more repsonsive.

**Comment by ridanoorain** [comment]
@KavyaBS123 Just give me some time I'm doing it

**Comment by ridanoorain** [comment]
Issue resolved
