### ISSUE TITLE
Increase size and add rounded corners to logo in header

### ISSUE THREAD

**Issue by rajdesai17** [07sumit1002/CabRental#4]
The current logo in the top left corner of the website appears to be quite small and has square corners. This makes it less visually appealing and potentially difficult to see on smaller screens.

Suggestion:

Increase the size of the logo slightly to improve visibility.
Add rounded corners to the logo to create a more modern and user-friendly aesthetic.
![Screenshot 2024-06-19 103719](https://github.com/07sumit1002/CabRental/assets/118588662/ffbb1190-0fd4-4d09-8a9d-484ed89778bc)

**Comment by 07sumit1002** [comment]
@rajdesai17 Go ahead and work on it.

**Comment by 07sumit1002** [comment]
Nice work
