### ISSUE TITLE
Create a .gitignore

### ISSUE THREAD

**Issue by deepesh611** [07sumit1002/CabRental#41]
@07sumit1002, we can add a file to remove unwanted folders from the repo. (such as .vscode)

**Comment by deepesh611** [comment]
@07sumit1002, Let me know if u need this. This file is usually used in big project repos, to reduce unwanted storage space

**Comment by 07sumit1002** [comment]
You can create it but It will be much work to do

**Comment by deepesh611** [comment]
> You can create it but It will be much work to do

it's not that big of a deal, but it's a good practice because, in the near future, you can add APIs to your project.
The APIs require certain files, like `config.json`, `credentials.json`, etc. to connect and allow only authenticated users, and youo cannot share these files as they are meant to be confidential. `.gitignore` comes to rescue in that situation as well

**Comment by deepesh611** [comment]
@07sumit1002 I have created a PR, pls have a look

https://github.com/07sumit1002/CabRental/pull/81
