### ISSUE TITLE
Create a setup file

### ISSUE THREAD

**Issue by deepesh611** [07sumit1002/CabRental#43]
A setup file that creates a new database and required tables, so that every contributor need not create it manually

**Comment by 07sumit1002** [comment]
@deepesh611 Go ahead and work on it

**Comment by 07sumit1002** [comment]
Actually the file got deleted but you can go through the .php file to get a idea of initial database and further can be made as per assumption.

**Comment by deepesh611** [comment]
alright, let me give it a shot. Just for teh sake of update, I would prefer .py for the setup file. If you want I can give it a shot in .sh or .ps1

**Comment by 07sumit1002** [comment]
sure go ahead in which ever you are comfortable

**Comment by deepesh611** [comment]
@07sumit1002 , I have added a PR, have a look

**Comment by deepesh611** [comment]
@07sumit1002 be sure to update the score if you havn't already
email: deepeshvcd6273@gmail.com

**Comment by 07sumit1002** [comment]
Assigned the points

**Comment by 07sumit1002** [comment]
check it
