### ISSUE TITLE
[Feature]: Login and SIgnup Page

### ISSUE THREAD

**Issue by AkshatPandey-2004** [07sumit1002/CabRental#46]
Hey I can add Login And Sign Up Page Instead of Admin page 
and can Make it responsive and attractive.

Label: Bonus

A Sample :-

![loginn](https://github.com/07sumit1002/CabRental/assets/114497044/e106c899-7157-4d43-9e4b-ababa6247cbb)

**Comment by 07sumit1002** [comment]
Proceed to work on it and integrate it with the database.
