### ISSUE TITLE
Adding a favicon to the website

### ISSUE THREAD

**Issue by Khanishsuresh** [07sumit1002/CabRental#5]
Adding of a Favicon icon

![image](https://github.com/07sumit1002/CabRental/assets/136162512/0381a560-5729-43ec-bb05-6fd137c74d77)

**Comment by Khanishsuresh** [comment]
hii @07sumit1002 ,

I would like to contribute to this issue
Would u please assign this issue under VSOC'24

**Comment by 07sumit1002** [comment]
@Khanishsuresh Go ahead and work on it.

**Comment by Khanishsuresh** [comment]
Hii @07sumit1002 ,

I have raised PR #33  for this issue
please accept the PR

**Comment by Khanishsuresh** [comment]
Hii @07sumit1002 

I have once again created the PR for this issue
PR #36 
please accept the PR

**Comment by Khanishsuresh** [comment]
Hii @07sumit1002 

The PR is been raised for this issue

The PR #40 
Please accept the PR
