### ISSUE TITLE
Add a Footer with Social Media Links, Contact Information, and Terms and Conditions

### ISSUE THREAD

**Issue by Yaser-123** [07sumit1002/CabRental#57]
As a part of improving the user experience and the overall design of the CabRental website, we need to add a footer section. This footer should include links to our social media profiles, contact information, and a link to our terms and conditions page.

Requirements:

Social Media Links:

Add icons/links for popular social media platforms (e.g., Facebook, Twitter, Instagram).
Ensure the links open in a new tab.
Contact Information:

Include an email address and a phone number for customer support.
Add a physical address if applicable.
Terms and Conditions:

Provide a link to the terms and conditions page.
Ensure the link is clearly labeled and easily accessible.
Design Specifications:

The footer should have a consistent design that aligns with the overall aesthetic of the website.
Use appropriate icons for social media links.
Ensure the footer is responsive and looks good on all devices.
Implementation Steps:

Create a new <footer> element at the bottom of the main HTML file.
Add a container for the social media links using <a> tags and icon images.
Include a section for contact information using <p> tags.
Add a link to the terms and conditions page using an <a> tag.
Style the footer using CSS to match the website's design.
This enhancement will improve the website's usability by providing essential information and easy access to our social media profiles.

**Comment by 07sumit1002** [comment]
check the deployed project, this has already been worked upon
