### ISSUE TITLE
Add a FAQ Section to the Website

### ISSUE THREAD

**Issue by Yaser-123** [07sumit1002/CabRental#58]
Issue Description:
To enhance user experience and provide quick answers to common queries, we need to add a Frequently Asked Questions (FAQ) section to the CabRental website.

**Requirements:**
1. **FAQ Layout**:
   - Create a dedicated section for FAQs on the homepage or a separate FAQ page.
   - Use a clean and user-friendly layout to display questions and answers.

2. **Accordion Functionality**:
   - Implement accordion functionality to hide and show answers when questions are clicked.
   - Ensure smooth transitions and a visually appealing design.

3. **Content**:
   - Include common questions related to the car rental process, pricing, policies, etc.
   - Provide clear and concise answers to each question.

**Design Specifications:**
- The FAQ section should match the overall aesthetic of the website.
- Use appropriate headings and styling to distinguish between questions and answers.
- Ensure the section is responsive and looks good on all devices.

**Implementation Steps:**
1. Create a new section in the HTML file for the FAQ.
2. Add markup for questions and answers, using `<div>` or `<ul>` elements.
3. Implement JavaScript to handle the accordion functionality, allowing questions to expand/collapse.
4. Style the FAQ section using CSS to make it visually appealing and consistent with the website's design.

Adding a FAQ section will help users find answers quickly, reducing the need for direct support and improving overall satisfaction.

**Comment by 07sumit1002** [comment]
@Yaser-123 Go ahead and work on it
