### ISSUE TITLE
Creating this project in react

### ISSUE THREAD

**Issue by Khanishsuresh** [07sumit1002/CabRental#6]
Hii @07sumit1002 ,

I would like to alter this project using react 
So it would be more dynamically used and it would be easily handled by other peoples

Would u please assign this issue to me under VSOC'24

**Comment by 07sumit1002** [comment]
@Khanishsuresh Go ahead and work on it.
for the time being I am giving it a medium tag but depending upon your scope of work, i will give bonus as well

**Comment by 07sumit1002** [comment]
@Khanishsuresh Also write about this issue in discord channel so that it will be easier for me to mention it in Spreadsheet.

**Comment by 07sumit1002** [comment]
https://discord.com/channels/1234877876382208082/1252619076522475530

**Comment by Khanishsuresh** [comment]
@07sumit1002 Done

**Comment by Khanishsuresh** [comment]
@07sumit1002 

Hii bro, I am working on this issue. I request you not to accept any PR for 1 day
So i will create the app in react, next the users can add there contribution in react

I am waiting for u reply. Once u say i will start doing it
But i need hardly one day.Since there are many files in ur project

**Comment by 07sumit1002** [comment]
Sure
