### ISSUE TITLE
[GENERAL] Scroll to top button is not showing

### ISSUE THREAD

**Issue by souvikpramanikgit** [07sumit1002/CabRental#600]
**Topic**
> A clear and concise description of the topic or question.

Scroll to top button is not showing

**Details**
> Provide more details or context about your topic or question.

Because of the chatbot the scroll to top button is not showing, so i want to move the scroll to top button to the left side of the chatbot button.

**Additional context**
> Add any other context or screenshots if necessary.

**Comment by AMOLJADHAV9** [comment]
HI @07sumit1002 
CAN YOU ASSIGN THIS ISSUE TO ME, I'LL FIX IT

**Comment by guptaarpita** [comment]
I am interested
