### ISSUE TITLE
Restoring website

### ISSUE THREAD

**Issue by 07sumit1002** [07sumit1002/CabRental#72]
The website has gone awry. So, we need to restore the website to its original form.
Label: Bonus
Points: up to 50

**Comment by Yaser-123** [comment]
I will do it assign me, (make the website as it was before few days)


https://github.com/07sumit1002/CabRental/assets/140265777/bc78b8c1-9aea-4d27-bd59-a12bd6269d44

similar to this

**Comment by 07sumit1002** [comment]
@Yaser-123 go ahead and work on it
