### ISSUE TITLE
How it works section can still be made more interactive

### ISSUE THREAD

**Issue by KavyaBS123** [07sumit1002/CabRental#9]
How it works now is great, But it can be made still better by adding hovering features and it seems to be monotonous due to continuation of divs side by side. It can be made one over other its looks best.
![Screenshot (462)](https://github.com/07sumit1002/CabRental/assets/148982177/d72a0616-b4ba-44da-9cca-ea3e90fe76d4)

**Comment by 07sumit1002** [comment]
@KavyaBS123 Go ahead and work on it.

**Comment by 07sumit1002** [comment]
Nice work

**Comment by 07sumit1002** [comment]
Check the points that have been awarded.
