### ISSUE TITLE
Improve FAQ Section: Plus Icon Not Visible & Add smooth radius to Question Boxes & correct spellings

### ISSUE THREAD

**Issue by Vishwajeet594** [07sumit1002/CabRental#97]
### Description: 
In the FAQ section of the website, the **plus icon** used for expanding the answers is not visible, and smooth border radius look on visuals and 

also **add s** on  **frequently ask question** heading.
### Issues:

1. The plus icon is not displayed properly.
2. Each FAQ question box currently lacks a border, making the section look less organized and harder to navigate.

### Before (Current View Without Plus Icon & Borders):
![Screenshot 2024-09-28 224426](https://github.com/user-attachments/assets/233f8fab-d385-4165-b12f-08a19dae8d7e)

### After (Expected View With Plus Icon & Borders):
![Screenshot 2024-09-28 224344](https://github.com/user-attachments/assets/12319a64-8d94-4c84-8908-77c5518e4aed)

### Steps to Reproduce:

1. Navigate to the FAQ section.
2. Notice that the plus icon is missing and each question lacks a border.
### Request: 
Please **assign this issue** to me, and I'll work on resolving it and **add required labels**

**Comment by 07sumit1002** [comment]
@Vishwajeet594 Go ahead and work on it
