### ISSUE TITLE
Contact Link Not Working in the Ride Section

### ISSUE THREAD

**Issue by Vishwajeet594** [07sumit1002/CabRental#98]
### Description: 
The contact link in the Ride section of the website is not functioning as expected. Clicking the link does not redirect the user to the intended page or trigger any action.

### Issue:
The contact link on the Ride section is non-functional. This affects user accessibility, as they cannot reach the contact page from this section.
### Screenshots:
![Screenshot 2024-09-28 231832](https://github.com/user-attachments/assets/842e4f90-8d92-468a-8b1a-88baa9b2defc)
### Current Behavior (Non-Working Contact Link):
![Screenshot 2024-09-28 231929](https://github.com/user-attachments/assets/6d98ed92-f806-4131-9e20-a84b8274d6c7)
### Request:
Please assign this issue to me, and I'll work on resolving it.

**Comment by ParasY1724** [comment]
Hello !! , Could you assign me this task would not take more than 2 minutes. Thanks !!

**Comment by apoorvxgoyalx** [comment]
hello, i would love to work on this task

**Comment by Devanshu1603** [comment]
can you assign this to me under gssoc ext level . would love to contribute

**Comment by Ananya200305** [comment]
Hello, I would like to work on this task under GSSOC
